# Generated by Django 6.0.6 on 2026-07-07 03:15

import closet.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Garment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('top', 'Blusa / Top'), ('bottom', 'Falda / Pantalón'), ('dress', 'Vestido'), ('outerwear', 'Abrigo / Chaqueta'), ('shoes', 'Zapatos'), ('bag', 'Bolso'), ('accessory', 'Accesorio')], max_length=20)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to=closet.models.garment_upload_path)),
                ('cutout', models.ImageField(blank=True, null=True, upload_to=closet.models.cutout_upload_path)),
                ('favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Outfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('occasion', models.CharField(blank=True, max_length=100)),
                ('items', models.JSONField(default=list)),
                ('favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
